apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  AWS_ENDPOINT_URL: "http://floci:4566"
  S3_BUCKET_NAME: {{ .Values.floci.bucketName | quote }}
  SQS_QUEUE_NAME: {{ .Values.floci.queueName | quote }}
  MAX_UPLOAD_SIZE_MB: {{ .Values.backend.maxUploadSizeMb | quote }}
