apiVersion: v1
kind: ResourceQuota
metadata:
  name: image-transformer-quota
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "20"
