apiVersion: v1
kind: Secret
metadata:
  name: floci-credentials
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.floci.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.floci.secretAccessKey | quote }}
  AWS_DEFAULT_REGION: {{ .Values.floci.region | quote }}
